#!/usr/bin/env python

import sys
try:
	import siptrackd_twisted
	import siptrackd_twisted.siptrackd
except ImportError, e:
    print >>sys.stderr, 'ERROR: unable to import siptrackd_twisted'
    print >>sys.stderr, 'verify that siptrackd_twisted is in you PYTHONPATH'
    raise

def main():
    sys.exit(siptrackd_twisted.siptrackd.main(sys.argv))

if __name__ == '__main__':
    main()
